#!/bin/bash
# chkconfig: 2345 18 82

### BEGIN INIT INFO
# Provides: rad
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Router Announcement 
# Description: Router Announcement Daemon 
### END INIT INFO

# source function library
. /lib/lsb/init-functions

RETVAL=0
PROG="rad"
cmd=/usr/sbin/rad
LOCK_FILE=/var/lock/rad
WATCH_OPTS="--loglevel info"
PID_FILE=/var/run/${PROG}/${PROG}.pid
LOG_FILE=/var/log/rad.log

case "$1" in
  start)
	log_daemon_msg "Starting Router Advertisement Daemon" "$PROG"
	mkdir -p /var/run/ratools
	mkdir -p /var/run/rad
	#start_daemon $cmd $WATCH_OPTS &
	/usr/sbin/rad $WATCH_OPTS >${LOG_FILE} 2>&1 &
	pid=$!
	sleep 1
	if [ -f /etc/rad.conf ]; then
	     echo ""
	     echo "Configuring $PROG"
	     /usr/bin/ractl < /etc/rad.conf
	fi
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
	    touch $LOCK_FILE
	    echo $pid >$PID_FILE
	fi
	log_end_msg $RETVAL
	;;
  stop)
	log_daemon_msg "Shutting down Router Advertisement Daemon" "$PROG"
	echo ""
	killall -w -s SIGINT $cmd 
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $LOCK_FILE $PID_FILE
	log_end_msg $RETVAL
	;;
  restart|reload|force-reload)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  condrestart|try-restart)
	if [ -f $LOCK_FILE ]; then
		$0 stop
		$0 start
	fi
	RETVAL=$?
	;;
  status)
	status_of_proc -p $PID_FILE $cmd
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status}"
	exit 2
esac

exit $RETVAL
